spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        transformacionSubscribableChannel:
          destination: conector1MessagesS1
          group: transformacionesPaso1IntakeGroupS1
          consumer:
            maxAttempts: 1
        transformacionMessagesChannel:
          destination: transformacionPaso1MessagesS1
          consumer:
            maxAttempts: 1
        transformacionMessagesChannelErrores:
          destination: conector1MessagesErrorS1
          consumer:
            maxAttempts: 1    
      
#        input:
#          destination: conector1MessagesS1
#          group: transformacionesPaso1IntakeGroupS1
#          consumer:
#            maxAttempts: 1
#        output:
#          destination: transformacionPaso1MessagesS1
#          consumer:
#            maxAttempts: 1

transformacion: 
  xslt:
    s1:
      paso1: xslt/minuscula.xsl
      paso2: xslt/mayuscula.xsl
      paso3: xslt/minuscula.xsl
      paso4: xslt/mayuscula.xsl
      paso5: xslt/minuscula.xsl
      
logging:
  config: ${configserver.discovered.uri}/logback/default/master/logback-spring.xml