spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
                    
logging:
  config: ${configserver.discovered.uri}/logback/default/master/logback-spring.xml