spring:
  rabbitmq:
    host: broker
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        conector1MessagesChannel:
          destination: conector1Messages
          consumer:
            maxAttempts: 1
        replayChannel:
          destination: replayChannel
          group: conector1QueueReplays
          consumer:
            maxAttempts: 1   
     
solucion:
  s1: 
    tipoComposicion: coreografia
  s2:
    tipoComposicion: orquestacion
    
logging:
  config: ${configserver.discovered.uri}/logback/default/master/logback-spring-docker.xml