spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        transformacionSubscribableChannel:
          destination: transformacionPaso3MessagesS1
          group: transformacionesPaso4IntakeGroupS1
          consumer:
            maxAttempts: 1
        transformacionMessagesChannel:
          destination: transformacionPaso4MessagesS1
          consumer:
            maxAttempts: 1
        transformacionMessagesChannelErrores:
          destination: conector1MessagesErrorS1
          consumer:
            maxAttempts: 1 
            
#        input:
#          destination: transformacionPaso3MessagesS1
#          group: transformacionesPaso4IntakeGroupS1
#          consumer:
#            maxAttempts: 1
#        output:
#          destination: transformacionPaso4MessagesS1
#          consumer:
#            maxAttempts: 1

transformacion: 
  xslt:
    s1:
      paso1: xslt/minuscula.xsl
      paso2: xslt/mayuscula.xsl
      paso3: xslt/minuscula.xsl
      paso4: xslt/mayuscula.xsl
      paso5: xslt/minuscula.xsl
solucion:
  s1: 
    tipoComunicacion: one-way
  s2:
    tipoComunicacion: req-resp      
logging:
  config: ${configserver.discovered.uri}/logback/default/master/logback-spring.xml