spring:
  rabbitmq:
    host: broker
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        enriquecedorSubscribableChannel:
          destination: transformacionjsonxmlMessages
          group: enriquecedorQueue
        enriquecedorMessagesChannel:
          destination: enriquecedorMessages
        enriquecedorMessagesChannelErrores:
          destination: replayMessages
    
enricher: 
  s1: 
    usuario: proygrado
    password: proygrado2019
  s2:
    usuario: proygrado
    password: proygrado2019
    
logging:
  config: ${configserver.discovered.uri}/logback/default/master/logback-spring-docker.xml