spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        conector1MessagesChannel:
          destination: conector1MessagesS1
          consumer:
            maxAttempts: 1
logging:
  config: ${configserver.discovered.uri}/logback/default/logback-spring.xml?useDefaultLabel