spring:
  rabbitmq:
    host: broker
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        conectorSalidaSubscribableChannel:
          destination: enriquecedorMessages
          group: conectorSalidaQueue
          consumer:
            maxAttempts: 1
        conectorSalidaMessagesChannel:
          destination: conectorSalidaMessages
          consumer:
            maxAttempts: 1
        conectorSalidaErrorsChannel:
          destination: replayMessages
          consumer:
            maxAttempts: 1
            
conectorSalida:
  s2:
    clienteWSDL: http://clientefinalsoap:9002/ws/empresas.wsdl
    requestParam1:  razonSocial
            
solucion:
  s1: 
    tipoComunicacion: one-way
  s2:
    tipoComunicacion: req-resp
  
    
logging:
  config: ${configserver.discovered.uri}/logback/default/master/logback-spring.xml