spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        correctasChannel:
          destination: transformacionMessagesFinalS1
          group: conector2IntakeGroupS1
          consumer:
            maxAttempts: 1
        respuestasChannel:
          destination: replayChannel
          consumer:
            maxAttempts: 1
            
conectorSalida:
  s2:
    clienteWSDL: http://localhost:8080/cliente2/services/ServicioPersona?wsdl
    requestParam1:  ci
            
solucion:
  s1: 
    tipoComunicacion: one-way
  s2:
    tipoComunicacion: req-resp
    clienteURL: http://localhost:9000/respuestaSolicitud
  
    
logging:
  config: ${configserver.discovered.uri}/logback/default/master/logback-spring.xml