spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/enriquecamejo/garbanzo.git/
          #uri: https://github.com/srast3/spring-kafka-microservice.git/
          search-paths:
              - "demo-properties/{application}"
         #    - "EmailServiceConfigProperties"
