spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/enriquecamejo/garbanzo.git/porotos/
          #uri: https://github.com/srast3/spring-kafka-microservice.git/
        #  search-paths:
             # - "porotos"
         #    - "EmailServiceConfigProperties"
